"""Pydantic schemas for API request/response validation."""
from datetime import datetime
from enum import Enum
from typing import Any, Optional
from uuid import UUID

from pydantic import BaseModel, Field, validator


# ─── Enums ────────────────────────────────────────────────────────────────────

class IntentType(str, Enum):
    RETENTION_INVESTIGATION = "retention_investigation"
    REVENUE_INVESTIGATION = "revenue_investigation"
    PAYMENT_FAILURE_INVESTIGATION = "payment_failure_investigation"
    CHURN_INVESTIGATION = "churn_investigation"
    FEATURE_IMPACT_INVESTIGATION = "feature_impact_investigation"
    ENGAGEMENT_INVESTIGATION = "engagement_investigation"
    GENERAL_ANALYTICS = "general_analytics"


class AnalysisType(str, Enum):
    COHORT_RETENTION = "cohort_retention"
    SEGMENT_COMPARISON = "segment_comparison"
    FUNNEL_ANALYSIS = "funnel_analysis"
    REVENUE_ANALYSIS = "revenue_analysis"
    CHURN_PREDICTION = "churn_prediction"
    ANOMALY_DETECTION = "anomaly_detection"
    ROOT_CAUSE = "root_cause"


class ChartType(str, Enum):
    LINE = "line"
    BAR = "bar"
    HEATMAP = "heatmap"
    SCATTER = "scatter"
    FUNNEL = "funnel"
    AREA = "area"
    DONUT = "donut"


class InvestigationStatus(str, Enum):
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


# ─── Common Schemas ───────────────────────────────────────────────────────────

class TimeRange(BaseModel):
    start: datetime
    end: datetime
    focus: Optional[str] = None
    comparison: Optional[str] = None

    class Config:
        json_schema_extra = {
            "example": {
                "focus": "last_week",
                "comparison": "previous_week"
            }
        }


class DataPoint(BaseModel):
    x: Any
    y: float | int
    label: Optional[str] = None
    metadata: dict[str, Any] = Field(default_factory=dict)


# ─── Chat Schemas ──────────────────────────────────────────────────────────────

class ChatContext(BaseModel):
    """User-provided context for filtering/scoping analysis."""
    filters: dict[str, Any] = Field(default_factory=dict)
    time_range: Optional[TimeRange] = None
    focus_segments: list[str] = Field(default_factory=list)


class ChatRequest(BaseModel):
    """Request schema for chat endpoint."""
    message: str = Field(..., min_length=1, max_length=2000)
    session_id: Optional[str] = None
    context: ChatContext = Field(default_factory=ChatContext)

    class Config:
        json_schema_extra = {
            "example": {
                "message": "Why did retention drop last week?",
                "session_id": "550e8400-e29b-41d4-a716-446655440000",
                "context": {
                    "filters": {"plan": "pro"}
                }
            }
        }


class ChatStreamEvent(BaseModel):
    """Server-sent event for streaming investigation updates."""
    type: str  # investigation_start | finding | thinking | complete | error
    agent: Optional[str] = None
    data: dict[str, Any] = Field(default_factory=dict)
    message: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)


# ─── Intent Schemas ────────────────────────────────────────────────────────────

class InvestigationPlan(BaseModel):
    """Structured investigation plan generated by Intent Agent."""
    intent_type: IntentType
    primary_metrics: list[str]
    time_range: Optional[dict[str, Any]] = None
    dimensions: list[str] = Field(default_factory=list)
    hypotheses: list[str] = Field(default_factory=list)
    required_analyses: list[AnalysisType]
    priority: str = "medium"
    reasoning: Optional[str] = None


# ─── Metric Schemas ────────────────────────────────────────────────────────────

class MetricDefinition(BaseModel):
    """Definition of a measurable metric."""
    name: str
    display_name: str
    description: str
    calculation: str
    table: str
    time_granularity: str
    unit: Optional[str] = None


class MetricValue(BaseModel):
    """A metric value at a point in time."""
    metric: str
    value: float
    period: str
    change: Optional[float] = None
    change_pct: Optional[float] = None
    is_significant: bool = False


# ─── SQL Schemas ───────────────────────────────────────────────────────────────

class QueryRequest(BaseModel):
    """Request to execute a SQL query."""
    question: str = Field(..., min_length=1, max_length=1000)
    response_format: str = "table"  # table | chart | summary

    class Config:
        json_schema_extra = {
            "example": {
                "question": "Show me DAU for the past 30 days",
                "response_format": "chart"
            }
        }


class QueryResult(BaseModel):
    """Result from SQL query execution."""
    query: str
    results: list[dict[str, Any]]
    row_count: int
    execution_time_ms: float
    columns: list[str]
    explanation: Optional[str] = None


class SQLGenerationResult(BaseModel):
    """Result from SQL Agent."""
    query: str
    is_safe: bool
    estimated_rows: Optional[int] = None
    execution_time_ms: Optional[float] = None
    results: list[dict[str, Any]] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


# ─── Analysis Schemas ─────────────────────────────────────────────────────────

class CohortData(BaseModel):
    """Data for a single cohort period."""
    period: str
    size: int
    retention: list[float]  # [1.0, 0.65, 0.52, ...]
    revenue: Optional[list[float]] = None


class CohortAnalysisResult(BaseModel):
    """Result from Cohort Analysis Agent."""
    cohort_type: str
    cohorts: list[CohortData]
    average_retention: list[float]
    insights: list[dict[str, Any]] = Field(default_factory=list)


class Segment(BaseModel):
    """A user segment with characteristics."""
    name: str
    definition: str
    user_count: int
    percentage: float
    characteristics: dict[str, Any] = Field(default_factory=dict)
    risk_level: Optional[str] = None  # low | medium | high


class SegmentationResult(BaseModel):
    """Result from Segmentation Agent."""
    segments: list[Segment]
    method: str  # behavioral | demographic | value_based | risk_based
    total_users: int
    recommendations: list[dict[str, Any]] = Field(default_factory=list)


# ─── Root Cause Schemas ────────────────────────────────────────────────────────

class Evidence(BaseModel):
    """A piece of evidence for a hypothesis."""
    type: str  # correlation | timing | statistical | anecdotal
    metric: Optional[str] = None
    value: Optional[Any] = None
    description: str
    confidence: float = Field(..., ge=0.0, le=1.0)


class Hypothesis(BaseModel):
    """A testable hypothesis for root cause analysis."""
    id: str
    description: str
    confidence: float = Field(..., ge=0.0, le=1.0)
    evidence: list[Evidence] = Field(default_factory=list)
    ruled_out: bool = False
    next_steps: list[str] = Field(default_factory=list)


class RootCauseResult(BaseModel):
    """Result from Root Cause Agent."""
    hypotheses: list[Hypothesis]
    root_cause: Optional[str] = None  # ID of primary hypothesis
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    summary: Optional[str] = None


# ─── Visualization Schemas ────────────────────────────────────────────────────

class ChartConfig(BaseModel):
    """Configuration for a chart."""
    type: ChartType
    title: str
    x_axis: Optional[str] = None
    y_axis: Optional[str] = None
    show_legend: bool = True
    color_scheme: str = "default"
    annotations: list[dict[str, Any]] = Field(default_factory=list)


class Visualization(BaseModel):
    """A visualization artifact."""
    id: str
    type: ChartType
    title: str
    data: list[DataPoint] | dict[str, Any]
    config: ChartConfig
    vega_spec: Optional[dict[str, Any]] = None  # Vega-Lite spec


# ─── Executive Summary Schemas ────────────────────────────────────────────────

class Recommendation(BaseModel):
    """An actionable recommendation."""
    action: str
    impact: str  # low | medium | high
    effort: str  # low | medium | high
    urgency: str  # low | medium | high
    owner: Optional[str] = None
    timeline: Optional[str] = None
    expected_outcome: Optional[str] = None


class ExecutiveSummary(BaseModel):
    """Executive summary of investigation findings."""
    summary: str
    key_findings: list[str]
    root_cause: Optional[str] = None
    recommendations: list[Recommendation]
    metrics_impact: Optional[dict[str, Any]] = None
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)


# ─── Investigation Schemas ─────────────────────────────────────────────────────

class InvestigationResponse(BaseModel):
    """Full investigation response returned to the user."""
    id: str
    question: str
    status: InvestigationStatus
    intent: Optional[InvestigationPlan] = None
    metrics: list[MetricValue] = Field(default_factory=list)
    cohort_analysis: Optional[CohortAnalysisResult] = None
    segmentation: Optional[SegmentationResult] = None
    root_cause: Optional[RootCauseResult] = None
    visualizations: list[Visualization] = Field(default_factory=list)
    executive_summary: Optional[ExecutiveSummary] = None
    started_at: datetime
    completed_at: Optional[datetime] = None
    tokens_used: Optional[int] = None
    cost_cents: Optional[int] = None


# ─── Dashboard Schemas ─────────────────────────────────────────────────────────

class KPIValue(BaseModel):
    """A KPI metric with current value and change."""
    value: float | int
    change: float  # Absolute change
    change_pct: float  # Percentage change
    trend: str  # up | down | flat
    is_good_change: bool  # Whether the direction is favorable


class DashboardAlert(BaseModel):
    """An alert shown on the dashboard."""
    metric: str
    severity: str  # info | warning | critical
    message: str
    value: float
    threshold: float
    detected_at: datetime


class DashboardResponse(BaseModel):
    """Response for dashboard view."""
    kpis: dict[str, KPIValue]
    alerts: list[DashboardAlert] = Field(default_factory=list)
    recent_investigations: list[dict[str, Any]] = Field(default_factory=list)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


# ─── Memory Schemas ────────────────────────────────────────────────────────────

class MemoryItem(BaseModel):
    """A stored memory/investigation summary."""
    id: str
    question: str
    summary: Optional[str] = None
    root_cause: Optional[str] = None
    started_at: datetime
    completed_at: Optional[datetime] = None
    similarity_score: Optional[float] = None


class MemorySearchResponse(BaseModel):
    """Response from memory search."""
    query: str
    results: list[MemoryItem]
    total: int